EsercizioAmazon.MVC/Models/ErrorViewModel.cs
using System;

namespace EsercizioAmazon.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EsercizioAmazon.MVC/Models/ProdottoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EsercizioAmazon.MVC.Models
{
    public class ProdottoViewModel
    {

        [Required]
        [DisplayName("Codice Prodotto")]
        public string Codice { get; set; }
        [Required]
        [DisplayName("Descrizione Prodotto")]
        public string Descrizione { get; set; }
        [Required]
        [DisplayName("Tipologia Prodotto")]
        public Tipologia _Tipo { get; set; }
        [Required]
        [DisplayName("Prezzo al Pubblico")]
        public decimal PrezzoPubblico { get; set; }
        [Required]
        [DisplayName("Prezzo Fornitore")]
        public decimal PrezzoFornitore { get; set; }
    }
    public enum Tipologia
    {
        Elettronica,
        Abbigliamento,
        Casalinghi
    }
}

EsercizioAmazon.MVC/Controllers/HomeController.cs
using EsercizioAmazon.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EsercizioAmazon.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EsercizioAmazon.MVC/Controllers/ProdottiController.cs
using EsercizioAmazon.Core.BusinessLayer;
using EsercizioAmazon.MVC.Helper;
using EsercizioAmazon.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EsercizioAmazon.MVC.Controllers
{
    public class ProdottiController : Controller
    {
        private readonly IMainBusinessLayer MainBL;
        public ProdottiController(IMainBusinessLayer mainBL)
        {
            MainBL = mainBL;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var prodotti = MainBL.GetAllProdotti();

            List<ProdottoViewModel> prodottiViewModel = new List<ProdottoViewModel>();

            foreach (var item in prodotti)
            {
                prodottiViewModel.Add(item.ToProdottoViewModel());
            }

            return View(prodottiViewModel);
        }

        [HttpGet("Prodotti/Details/{codice}")]
        public IActionResult Details(string code)
        {
            var prodotto = MainBL.GetAllProdotti().FirstOrDefault(p => p.Codice == code);

            var prodottoViewModel = prodotto.ToProdottoViewModel();

            return View(prodottoViewModel);
        }

        #region Create

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ProdottoViewModel prodottoViewModel)
        {
            if (ModelState.IsValid)
            {
                var prodotto = prodottoViewModel.ToProdotto();
                MainBL.InserisciNuovoProdotto(prodotto);
                return RedirectToAction(nameof(Index))
;
            }
            return View(prodottoViewModel);
        }
        #endregion

        #region Edit

        [HttpGet]
        public IActionResult Edit(string id)
        {
            var prodotto = MainBL.GetAllProdotti().FirstOrDefault(p => p.Codice == id);
            var prodottoViewModel = prodotto.ToProdottoViewModel();
            return View(prodottoViewModel);
        }

        [HttpPost]
        public IActionResult Edit(ProdottoViewModel prodottoViewModel)
        {
            if (ModelState.IsValid)
            {
                var prodotto = prodottoViewModel.ToProdotto();
                MainBL.ModificaProdotto(prodotto.Codice, prodotto.Descrizione, prodotto._Tipologia,prodotto.PrezzoPubblico);
                return RedirectToAction(nameof(Index));
            }
            return View(prodottoViewModel);

        }
        #endregion

        #region Delete
        [HttpGet]
        public IActionResult Delete(string id)
        {
            var prodotto = MainBL.GetAllProdotti().FirstOrDefault(p => p.Codice == id);
            var prodottoViewModel = prodotto.ToProdottoViewModel();
            return View(prodottoViewModel);
        }

        [HttpPost]
        public IActionResult Delete(ProdottoViewModel prodottoViewModel)
        {
            if (ModelState.IsValid)
            {
                var prodotto = prodottoViewModel.ToProdotto();
                MainBL.EliminaProdotto(prodotto.Codice);
                return RedirectToAction(nameof(Index));
            }
            return View(prodottoViewModel);
        }
        #endregion
    }
}

EsercizioAmazon.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EsercizioAmazon.MVC/Views/Prodotti/Create.cshtml
@model ProdottoViewModel
<p>Inserisci un nuovo Prodotto</p>

<form method="post">
    <div class="form-group">
        <label asp-for="Codice"></label>
        <input asp-for="Codice" class="form-control" />
        <span asp-validation-for="Codice" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Descrizione"></label>
        <input asp-for="Descrizione" class="form-control" />
        <span asp-validation-for="Descrizione" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="_Tipo"></label>
        <select asp-for="_Tipo" asp-items="@ViewBag._Tipo" class="form-control">
            <option valute="">Seleziona un'opzione...</option>
        </select>
        <span asp-validation-for="_Tipo" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PrezzoPubblico"></label>
        <input asp-for="PrezzoPubblico" class="form-control" />
        <span asp-validation-for="PrezzoPubblico" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PrezzoFornitore"></label>
        <input asp-for="PrezzoFornitore" class="form-control" />
        <span asp-validation-for="PrezzoFornitore" class="text-danger"></span>
    </div>

    <input type="submit" value="Inserisci" class="btn btn-primary" />
    <input type="reset" value="Reset" class="btn btn-primary" />
    <a class="btn btn-primary" asp-action="Index" role="button">Indietro</a>

</form>

EsercizioAmazon.MVC/Views/Prodotti/Delete.cshtml
@model ProdottoViewModel

<p> Sei sicuro di voler eliminare il prodotto @Model.Codice - @Model.Descrizione</p>

<form method="post">
    <div class="form-group">
        <label asp-for="Codice"></label>
        <input asp-for="Codice" class="form-control" readonly />
        <span asp-validation-for="Codice" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Descrizione"></label>
        <input asp-for="Descrizione" class="form-control" readonly />
        <span asp-validation-for="Descrizione" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="_Tipo"></label>
        <select asp-for="_Tipo" asp-items="@ViewBag._Tipo" class="form-control" readoly>
            <option valute="">Seleziona un'opzione...</option>
        </select>
        <span asp-validation-for="_Tipo" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PrezzoPubblico"></label>
        <input asp-for="PrezzoPubblico" class="form-control" readonly />
        <span asp-validation-for="PrezzoPubblico" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PrezzoFornitore"></label>
        <input asp-for="PrezzoFornitore" class="form-control" readonly />
        <span asp-validation-for="PrezzoFornitore" class="text-danger"></span>
    </div>

    <input type="submit" value="Eliminazione" class="btn btn-danger" />
    <a class="btn btn-primary" asp-action="Index" role="button">Annulla</a>

</form>

EsercizioAmazon.MVC/Views/Prodotti/Details.cshtml
@model ProdottoViewModel
<h1>Ecco i dettagli del prodotto @Model.Codice</h1>
<p>Descrizione: @Model.Descrizione</p>
<p>Prezzo: @Model.PrezzoPubblico</p>

EsercizioAmazon.MVC/Views/Prodotti/Edit.cshtml
@model ProdottoViewModel
<h1>Modifica un prodotto</h1>

<form method="post">
    <div class="form-group">
        <label asp-for="Codice"></label>
        <input asp-for="Codice" class="form-control" readonly/>
        <span asp-validation-for="Codice" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Descrizione"></label>
        <input asp-for="Descrizione" class="form-control" />
        <span asp-validation-for="Descrizione" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="_Tipo"></label>
        <select asp-for="_Tipo" asp-items="@ViewBag._Tipo" class="form-control">
            <option valute="">Seleziona un'opzione...</option>
        </select>
        <span asp-validation-for="_Tipo" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PrezzoPubblico"></label>
        <input asp-for="PrezzoPubblico" class="form-control" />
        <span asp-validation-for="PrezzoPubblico" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PrezzoFornitore"></label>
        <input asp-for="PrezzoFornitore" class="form-control" readonly />
        <span asp-validation-for="PrezzoFornitore" class="text-danger"></span>
    </div>

    <input type="submit" value="Modifica" class="btn btn-primary" />
    <input type="reset" value="Reset" class="btn btn-primary" />
    <a class="btn btn-primary" asp-action="Index" role="button">Indietro</a>

</form>

EsercizioAmazon.MVC/Views/Prodotti/Index.cshtml
@model List<ProdottoViewModel>

    <h1> Ecco la lista dei Prodotti</h1>

    <a class="btn btn-primary" asp-controller="Prodotti" asp-action="Create" type="button">Inserisci nuovo Prodotto</a>

    <table class="table table-hover table-bordered table table-striped">
        <thead>
            <tr>
                <th>Codice</th>
                <th>Tipologia</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Codice</td>
                    <td>@item._Tipo</td>
                    <th>
                        <a asp-controller="Prodotti" asp-action="Edit" asp-route-id="@item.Codice" class="btn btn-primary">Modifica</a>
                        <a asp-controller="Prodotti" asp-action="Details" asp-route-id="@item.Codice" class="btn btn-primary">Visualizza Dettagli</a>
                        <a asp-controller="Prodotti" asp-action="Delete" asp-route-id="@item.Codice" class="btn btn-danger">Elimina</a>
                    </th>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <th>Totale</th>
                <th>@Model.Count</th>
                <th></th>
            </tr>
        </tfoot>
    </table>

EsercizioAmazon.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EsercizioAmazon.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EsercizioAmazon.MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Prodotti" asp-action="Index">Prodotti</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EsercizioAmazon.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>